improved and unified success and failure messages

diff --git a/src/main/script/readonly b/src/main/script/readonly
--- a/src/main/script/readonly
+++ b/src/main/script/readonly
@@ -12,3 +12,8 @@ JAVA=$("$APPDIR/helpers/set-java" java "$APPDIR/jrex/bin/java") || exit 1
 # gui=true                    | default: false - true to show server GUI
 # temp=<temp dir>             | default: 'dedupfs-temp' in the user's temp dir
 $JAVA "-DLOG_BASE=$APPDIR/log" -Xmx80m -Dfile.encoding=UTF-8 -Dlogback.configurationFile=logback-server.xml -cp "$APPDIR/lib/*:$APPDIR/lib-h2/*" dedup.mount readOnly=true "$@"
+ERRORLEVEL=$?
+if [ $ERRORLEVEL -ne 0 ]; then
+  echo "Dedupfs process finished with error code $ERRORLEVEL, exiting..."
+  exit $ERRORLEVEL
+fi
diff --git a/src/main/script/reclaim-space b/src/main/script/reclaim-space
--- a/src/main/script/reclaim-space
+++ b/src/main/script/reclaim-space
@@ -7,3 +7,10 @@ JAVA=$("$APPDIR/helpers/set-java" java "$APPDIR/jrex/bin/java") || exit 1
 # repo=<repository directory>       | default: '..' (parent of working directory)
 # keepDays=<number of days to keep> | default: 0 - the 'keepDays=' prefix can be omitted
 $JAVA "-DLOG_BASE=$APPDIR/log" -Xmx256m -cp "$APPDIR/lib/*:$APPDIR/lib-h2/*" dedup.reclaimSpace "$@"
+ERRORLEVEL=$?
+if [ $ERRORLEVEL -ne 0 ]; then
+  echo "Reclaim space finished with error code $ERRORLEVEL, exiting..."
+  exit $ERRORLEVEL
+fielse
+  echo "Reclaim space finished successfully."
+fi
diff --git a/src/main/script/stats b/src/main/script/stats
--- a/src/main/script/stats
+++ b/src/main/script/stats
@@ -6,3 +6,9 @@ JAVA=$("$APPDIR/helpers/set-java" java "$APPDIR/jrex/bin/java") || exit 1
 ### Parameters ###
 # repo=<repository directory>     | default: '..' (parent of working directory)
 $JAVA "-DLOG_BASE=$APPDIR/log" -Xmx256m -cp "$APPDIR/lib/*:$APPDIR/lib-h2/*" dedup.stats "$@"
+if [ $ERRORLEVEL -ne 0 ]; then
+  echo "Statistics finished with error code $ERRORLEVEL, exiting..."
+  exit $ERRORLEVEL
+fielse
+  echo "Statistics finished successfully."
+fi
